### ISSUE TITLE
Is there a reason rmp-serde 0.12.0 hasn't been published?

### ISSUE THREAD

**Issue by quadrupleslap** [3Hren/msgpack-rust#100]
Sorry if I'm missing something, but the fact that `rmp-serde` is still on `serde v0.8` is causing me lots of dependency problems.

**Comment by 3Hren** [comment]
I haven't implemented recursion limit protection, which I've dropped since the last release for some incompatibility reasons. But I think it can be done in further patches.

**Comment by dtolnay** [comment]
FWIW, we released recursion limit protection in a patch version of serde_json and nobody complained.

**Comment by 3Hren** [comment]
Oh, great! I'll take a look.

**Comment by 3Hren** [comment]
Anyway I just published new version on crates.io.
