### ISSUE TITLE
Utf8Error when parsing msgpack v4.0 encoded raw fields

### ISSUE THREAD

**Issue by awh** [3Hren/msgpack-rust#102]
The previous version of the msgpack spec ([v4.0](https://github.com/msgpack/msgpack/blob/acbcdf6b2a5a62666987c041124a10c69124be0d/spec-old.md?#raw-bytes)) does not have the concept of UTF-8 strings - only a 'raw' type which admits any binary data. In the [v5.0](https://github.com/msgpack/msgpack/blob/0b8f5ac67cdd130f4d4d4fe6afb839b989fdb86a/spec.md?#str-format-family) revision the markers used by msgpack to indicate 'raw' data in v4.0 were repurposed (yes really) to mean UTF-8 strings, and a new set of markers for binary data were introduced; consequently, if you attempt to parse msgpack data from a 4.0 compliant implementation in strict accordance with the 5.0 spec, it is possible to receive `Utf8Error`:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error(Utf8Error { valid_up_to: 5 })'
```

Could we get a field attribute that allows string fields to be interpreted as binary so that old msgpack files can be parsed successfully?

**Comment by awh** [comment]
The current spec also has this to say under [limitations](https://github.com/msgpack/msgpack/blob/master/spec.md#limitation):

* String objects may contain invalid byte sequence and the behavior of a deserializer depends on the actual implementation when it received invalid byte sequence
    * Deserializers should provide functionality to get the original byte array so that applications can decide how to handle the object

**Comment by 3Hren** [comment]
`Utf8Error` has [valid_up_to](https://doc.rust-lang.org/stable/std/str/struct.Utf8Error.html#method.valid_up_to) method, which can be used to index valid UTF8 sequence.

For this issue I need more context. Do you use serde or what?

**Comment by awh** [comment]
Motivating use case:
* I am trying to use rmp-serde to decode msgpack files that have been encoded with https://github.com/ugorji/go
* These msgpack files contain Golang [`time.Time`](https://golang.org/src/time/time.go?s=1853:2367#L29) structs encoded as binary strings (as specified [here](https://github.com/ugorji/go/blob/master/codec/time.go#L54-L102))
* `ugorji/go` is encoding the binary array as a raw field as described in [version 4.0 of the msgpack specification](https://github.com/msgpack/msgpack/blob/acbcdf6b2a5a62666987c041124a10c69124be0d/spec-old.md?#raw-bytes)
* `rmp` is attempting to decode these fields as UTF-8 strings, because [version 5.0 of the msgpack specification](https://github.com/msgpack/msgpack/blob/0b8f5ac67cdd130f4d4d4fe6afb839b989fdb86a/spec.md?#str-format-family) changed the meaning of the raw tag to mean 'UTF-8 encoded string' instead of 'arbitrary binary data'. Obviously this fails in the case where a 4.0 compliant encoder recorded arbitrary binary data that is not valid UTF-8

Other msgpack implementations have tripped over this issue:

From https://pypi.python.org/pypi/msgpack-python

> In old days, msgpack doesn’t distinguish string and binary types .. the type for represent string and binary types is named raw ... msgpack can distinguish string and binary type for now ... But msgpack renamed raw to str and added bin type. It is because keep compatibility with data created by old libs. raw was used for text more than binary.
> Currently, while msgpack-python supports new bin type, default setting doesn’t use it and decodes raw as bytes instead of unicode
```

From https://ludocode.github.io/mpack/md_docs_protocol.html

**Comment by awh** [comment]
@3Hren do you think this is something you will address?

**Comment by 3Hren** [comment]
Eventually yes. You can help with PR, of course.

**Comment by 3Hren** [comment]
Partially done in https://github.com/3Hren/msgpack-rust/pull/103 for `rmpv` crate. For serde integration I need more time to investigate.

**Comment by 3Hren** [comment]
@awh PTAL https://github.com/3Hren/msgpack-rust/pull/103 and https://github.com/3Hren/msgpack-rust/pull/109

**Comment by awh** [comment]
@3Hren sorry I didn't respond sooner - thanks, will give it a try and let you know how I get on!

**Comment by tubzby** [comment]
Sorry to comment on a closed issue, is this confirmed to be fixed? because I have met this error again.

I have a Golang server deployed using: https://github.com/ugorji/go, with a struct defined like this
```golang
type Data struct {
	Dst  net.IP
	Data []byte
}
```
the Dst field is encoded as string in new spec, which cause my rust client to panic with error: 
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error(Utf8Error { valid_up_to: 3, error_len: Some(1) })', src/conn/conn.rs:260:83
```

I'm using rmp-serde="0.15.4" and serde = "1.0.126"

**Comment by kornelski** [comment]
You will get UTF-8 decoding errors if you use `String` in Rust, and there's no fix for it — this type is always UTF-8, no exceptions.

You can decode non-string data into the [Raw](https://docs.rs/rmp-serde/0.15.5/rmp_serde/struct.Raw.html) type.

**Comment by tubzby** [comment]
Thanks, I have tried an alternative on thread #280
