### ISSUE TITLE
The trait bound `rmpv::decode::value::Error: std::error::Error` is not satisfied

### ISSUE THREAD

**Issue by dflemstr** [3Hren/msgpack-rust#105]
Errors need to implement `std::error::Error` to be part of generic error handling (e.g. when using `error-chain`).  I'd just like to file this issue because I won't get around to fixing it myself right now, but I might have time to fix it at a later point.

**Comment by 3Hren** [comment]
Done in https://github.com/3Hren/msgpack-rust/pull/103: https://github.com/3Hren/msgpack-rust/pull/103/files#diff-48381a7593311e7ddc202ef27ec1a4feR30.
