### ISSUE TITLE
Incompatibility with Java messagepack implementation

### ISSUE THREAD

**Issue by saarw** [3Hren/msgpack-rust#107]
Serializing a simple nested data structure with Rust and deserializing it with Java's implementation does not work. I am not sure if this is a problem in Rust's or Java's implementation, my use of types,  or because the implementations support different versions of the protocol, but perhaps someone here can help me figure it out?

I have created a reproducer with Java and Rust projects at https://github.com/saarw/msgpacktest

The structure I am serializing consists of an Outer struct/class containing a list of instances of an Inner struct/class and Rust seems to serialize the nested structure as simply [[["val1"],["val2"]], while Java serializes the same structure as {"inners":[{"value":"val1"},{"value":"val2"}]}

**Comment by 3Hren** [comment]
Since MessagePack doesn't specify how to serialize language's structs, we chose the most compact implementation (as tuples without field names). However there is a way to do what you want: https://github.com/3Hren/msgpack-rust/blob/master/rmp-serde-tests/tests/derive/se.rs#L130.

**Comment by saarw** [comment]
Ok, thanks! Tuples as structs is indeed nice and compact, but I guess I should use your solution for maps if I want the broadest possible language compatibility.
