### ISSUE TITLE
rmp 0.8.4 fails to build on Rust 1.13

### ISSUE THREAD

**Issue by bluss** [3Hren/msgpack-rust#111]
This is just a report of an incident, probably just due to changing the required Rust version in a patch release.

```rust
error: `..` in tuple struct patterns is experimental (see issue #33627)
  --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/rmp-0.8.4/src/decode/str.rs:30:13
   |
30 |             DecodeStringError::InvalidUtf8(.., ref err) => Some(err),
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
error: aborting due to previous error
```

Found in travis job https://travis-ci.org/bluss/rust-ndarray/jobs/210120040  (from ndarray's serialization tests). It only impacts CI, not the ndarray crate itself.

For comparison, rmp 0.8.2 [(ndarray CI)](https://travis-ci.org/bluss/rust-ndarray/jobs/207752232) compiled fine.

**Comment by bluss** [comment]
If you indicate fix or no fix, I'll update my CI accordingly.

**Comment by 3Hren** [comment]
Hi. Thanks for the report!

Sadly, that minimum Rust version can't be specified in Cargo.toml. I'll try to fix this if it's not too complex.

**Comment by bluss** [comment]
Thank you!
