### ISSUE TITLE
Возможность формирования Value из набора байт

### ISSUE THREAD

**Issue by LooMaclin** [3Hren/msgpack-rust#112]
Предлагаю добавить возможность формирования Value из набора байт
Чтобы можно было что-нибудь наподобие вот этого:
```rust
Value::from(&[0xa1][..])
Value::from([0xa1])
```

Так можно будет эффективно совмещать формирование конечного Value для сериализации из динамических данных и данных значения которых известно на этапе компиляции.

Вот конкретный пример где я не могу перевести сериализацию полностью на плечи этой библиотеки:
https://github.com/LooMaclin/tarantool_rs/blob/master/src/upsert.rs#L35

Префикс для строки msgpack с фиксированной длиной в 1 символ известен заранее и есть уже десериализованные константные значения этого единственного символа.

**Comment by 3Hren** [comment]
Я недавно довольно крупно апнул `rmpv`, в частности добавил кучу конверсий, и совместимость с древними запаковщиками. Кажется, частично из того, что ты хочешь - уже есть.

Насчет этого тикета немного не понятно, ты хочешь из уже корректного заенкоженного массива байт получить `Value`? Если так, то https://docs.rs/rmpv/0.3.0/rmpv/decode/value/fn.read_value.html - то, что надо.

**Comment by LooMaclin** [comment]
@3Hren да, ты правильно понял. это вроде то что нужно. проглядел видимо я эти моменты. спасибо. сейчас попробую

**Comment by LooMaclin** [comment]
@3Hren перевёл тарантул коннектор на `0.3.0` и сериализацию полностью перевёл на `Value::from`, теперь только в паре мест юзаю `read_value`. спасибо за помощь. таску закрываю.
