### ISSUE TITLE
A struct serialized as an array of fields

### ISSUE THREAD

**Issue by vorner** [3Hren/msgpack-rust#114]
I'm not 100% sure this is a bug, but looking at the code, it seems it is not the intention. Let's have a code:

```rust
extern crate rmp_serde;
extern crate rmpv;
#[macro_use]
extern crate serde_derive;

use rmp_serde::to_vec;
use rmpv::decode::read_value;

#[derive(Serialize)]
struct Test {
    field: usize,
    another: String,
}

fn main() {
    let data = Test {
        field: 42,
        another: "Hello".to_owned(),
    };
    let vec = to_vec(&data).unwrap();
    let val = read_value(&mut vec.as_slice()).unwrap();
    println!("{}", val);
}
```

And it prints: `[42, "Hello"]`. That isn't entirely incorrect and could be one of the possible ways to serialize it and deserializing it again works. However, when I look [into the code](https://docs.rs/rmp-serde/0.12.2/src/rmp_serde/encode.rs.html#229), I'd expect something like `[("field": 42), ("another": "Hello")]` (eg. using a map, with the field names). It would also be compatible with what `serde-json` does.

Is this the intention and I read the code differently, or is this a bug somewhere? Is the other way possible somehow, maybe by configuring the serializer somehow before using it?

**Comment by 3Hren** [comment]
It is intentionally that by default we pack structs using compact representation (as tuples). However there is a way to make what you want, check [this](https://github.com/3Hren/msgpack-rust/blob/master/rmp-serde-tests/tests/encode.rs#L136).
I see that it's common question, so I'd like to keep this issue opened until I provide a better way to select struct serialization behavior or/and better docs.

**Comment by vorner** [comment]
Alright, that looks good enough. And yes, a bit more documentation (or possibly having that `StructMapWriter` as part of the code and having a specialized constructor, just like there's `::new`) would also be nice.

**Comment by hjiayz** [comment]
But if I don't need a name. I can use tuples.
