### ISSUE TITLE
Имеется ли возможность создавать Value::Map и Value::Array из массивов, а не векторов?

### ISSUE THREAD

**Issue by LooMaclin** [3Hren/msgpack-rust#115]
Имеется ли возможность создавать Value::Map и Value::Array из массивов а не векторов?

Вот место где хочу избавиться от выделения памяти:
https://github.com/LooMaclin/tarantool_rs/blob/master/src/insert.rs#L22

Аналогичных много.

**Comment by 3Hren** [comment]
Value - владеющий объект, без аллокаций только мувать.
ср, 15 марта 2017 г. в 21:10, Arsen Galimov <notifications@github.com>:

**Comment by LooMaclin** [comment]
@3Hren хотелось бы полностью от них избавиться и при сериализации писать в фиксированного размера массив размер которого вынести как параметр компиляции библиотеки. ищу путь для реализации этого. может подскажешь что-нибудь?

**Comment by 3Hren** [comment]
Владение необходимо, чтобы нормально десериализацию делать. Вообще `Value` задумывался как "удобный" объект для хранения, сериализации/десериализации.

Для более быстрой десериализации без копирования строк есть `ValueRef`, но он тем не менее требует аллокаций под хранение массивов/мапочек, т.е. не подойдет. Без этих аллокаций десериализацию сделать невозможно, точнее можно, но это будет лапша из колбэков и взрыв стека при больших массивах.

Фиксированного размера массив - это все-таки отдельный тип, а с π-типами в Расте не сложилось. Если и хранить, то слайс, но тут наткнешься на проблемы с лайфтаймами. Можно наверно попытаться сделать что-то подобное чисто для сериализации.
