### ISSUE TITLE
rmp-serde fails to build on Rust 1.13

### ISSUE THREAD

**Issue by bluss** [3Hren/msgpack-rust#118]
rmp-serde fails to build on Rust 1.13

Error message:

```rust
error: `..` in tuple patterns is experimental (see issue #33627)
   --> /home/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/rmp-serde-0.12.3/src/lib.rs:107:17
    |
107 |             Err((.., ref err)) => Some(&err),
    |                 ^^^^^^^^^^^^^
```

Travis log: https://travis-ci.org/bluss/rust-ndarray/jobs/215268437

You should document and test the minimum version of Rust that you support.

**Comment by 3Hren** [comment]
Those tuple patterns are awesome, cannot resist.
Fixed and republished rmp-serde=0.12.4 and rmpv=0.3.5

**Comment by bluss** [comment]
:smile: Thanks!

**Comment by 3Hren** [comment]
Also noted in README.md and added 1.13.0 version in travis.yml to be sure that this will no longer be a problem.

Thanks for the report!
