### ISSUE TITLE
Add to msgpack.org

### ISSUE THREAD

**Issue by sunjay** [3Hren/msgpack-rust#119]
This is the msgpack implementation recommended by serde, but it doesn't show up on the msgpack site. It would be great if it could be there as well. 

There are some instructions here: https://github.com/msgpack/website/blob/master/README.md#how-to-list-up-your-project-on-msgpackorg

Looks like you basically just need to add this to the repo description: `msgpack.org[Rust]`

**Comment by 3Hren** [comment]
But it's already there. At the bottom for some reasons.

![image](https://cloud.githubusercontent.com/assets/969900/25092684/786469b6-2397-11e7-989f-77a29f6cc5be.png)

**Comment by sunjay** [comment]
Oh my bad! Must be why I didn't see that. That sucks. Your implementation seems to actually be maintained.
