### ISSUE TITLE
Releasing a Serde 1.0 crate

### ISSUE THREAD

**Issue by drusellers** [3Hren/msgpack-rust#125]
Is there anything I can do to help get a crate released that supports Serde 1.0?

**Comment by 3Hren** [comment]
Probably nothing, it is more or less ready at this moment. The last thing I need is to review entire crate again. Will do it today.

**Comment by 3Hren** [comment]
^ that's for `rmp-serde` crate.

For `rmpv` crate right now I'm trying to implement `Deserializer` for `&ValueRef` (which already exists for both `Value` and `ValueRef`) without copy-pasting code, which seems to be tricky...

**Comment by dtolnay** [comment]
Yeah serde_json needed two different Deserializer implementations for Value vs &Value. Curious to see what you come up with.

**Comment by 3Hren** [comment]
Well, I ended with HRTB, artificial abstract traits with 5 or 6 associated types and spaghetti code.

Copy-pasting is easier to maintain than those things :D.

**Comment by drusellers** [comment]
Sweet. Let me know if there is anything I can do to help.

**Comment by 3Hren** [comment]
Landed: https://crates.io/crates/rmp-serde, https://crates.io/crates/rmpv

**Comment by drusellers** [comment]
YAS
