### ISSUE TITLE
missing implementation of emit_enum

### ISSUE THREAD

**Issue by godfryd** [3Hren/msgpack-rust#13]
Hello,

It would be nice to be able encode and decode enums.
When it could be expected?

Regards,
Godfryd

**Comment by 3Hren** [comment]
You can check this functionality https://github.com/3Hren/msgpack-rust/releases/tag/v0.3.0 but I'm not sure it's a finally version. I'll keep thinking about it for 1-2 more days.

**Comment by godfryd** [comment]
It looks that it works for my case.
Thanks :)
