### ISSUE TITLE
build failures in recent nightly

### ISSUE THREAD

**Issue by mattmacy** [3Hren/msgpack-rust#134]
The following code: 
```
    pub fn load<'a, P, T: 'a + Deserialize<'a>>(path: P) -> io::Result<Vec<T>>
        where P: AsRef<Path>
    {
        let mut buffer = File::open(path)?;
        let mut encoded = Vec::new();
        let size = buffer.read_to_end(&mut encoded)?;
        if size == 0 {
            return Err(Error::new(ErrorKind::UnexpectedEof, "Empty File"));
        };
        let mut de = Deserializer::new(&encoded[..]);
        let decoded = Deserialize::deserialize(&mut de).expect("decode failed");
        Ok(decoded)
    }
```

Compiled with a nightly from as recently as last week, now fails with:

error: type `rmps::decode::ReadReader<&[u8]>` is private
  --> src/torch/serde.rs:28:18
   |
28 |     let mut de = Deserializer::new(&encoded[..]);
   |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: type `rmps::decode::ReadReader<&[u8]>` is private
  --> src/torch/serde.rs:29:44
   |
29 |     let decoded = Deserialize::deserialize(&mut de).expect("decode failed");
   |                                            ^^^^^^^

error: type `rmps::decode::ReadReader<&[u8]>` is private
  --> src/torch/serde.rs:29:19
   |
29 |     let decoded = Deserialize::deserialize(&mut de).expect("decode failed");
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 3 previous errors

**Comment by 3Hren** [comment]
I've published these changes. Please check again.
