### ISSUE TITLE
Rust ints of the same type serialized to different lengths

### ISSUE THREAD

**Issue by modalduality** [3Hren/msgpack-rust#137]
Consider this code:
```
extern crate serde;
extern crate rmp_serde;

use serde::{Deserialize, Serialize};
use rmp_serde::{Deserializer, Serializer};

fn msgpack_int(a: u64) {
    let mut buf = Vec::new();
    a.serialize(&mut Serializer::new(&mut buf)).unwrap();
    println!("int {:?} serialized to {:?} bytes", a, buf.len());
}

fn main() {
    msgpack_int(0);
    msgpack_int(256);
    msgpack_int(65536);
}
```

The output is 
```
int 0 serialized to 1 bytes
int 256 serialized to 3 bytes
int 65536 serialized to 5 bytes
```

Discovered by just inspecting the code: serializing an int automatically chooses a smaller messagepack int size if the int is small enough (https://github.com/3Hren/msgpack-rust/blob/master/rmp/src/encode/uint.rs#L138-L152).

I'm using messagepack to serialize data for cryptography, and it's important that everything with the same type is the same width when serialized.

Can there be an option to choose the messagepack type that's exactly the same size as the Rust type in serialization? I can code this and submit a PR if people think this is a good idea. Is there a better way to accomplish what I'm trying to do?

**Comment by SX91** [comment]
MessagePack itself is _packed_ representation of data, so compact representation is enforced by the [specification](https://github.com/msgpack/msgpack/blob/master/spec.md) as described right above the function you highlighted.

Spec says: 

> If an object can be represented in multiple possible output formats, serializers SHOULD use the format which represents the data in the smallest number of bytes.

MsgPack is not suited for your task, unfortunately.

**Comment by SX91** [comment]
@3Hren you could close this as non-issue.
