### ISSUE TITLE
No way to Deserialize to struct if invalid-utf8 in string

### ISSUE THREAD

**Issue by d3zd3z** [3Hren/msgpack-rust#143]
There doesn't seem to be a way to deserialize to a structure (rmp-serde) if the msgpack data has binary data as a string. Unfortunately, it seems that Python code likes to do this.

I've tried having my field as a `Vec<u8>`, but I still get a `Utf8Error` when decoding. I can post an example if that is useful.

**Comment by 3Hren** [comment]
[This](https://docs.rs/rmp-serde/0.13.6/rmp_serde/struct.Raw.html) struct is exactly what you want.

**Comment by d3zd3z** [comment]
That does work for decode, but now the struct cannot implement Serialize. It seems a bit clumsy to have to then migrate the data over to another struct, but at least I have a workaround.

**Comment by 3Hren** [comment]
Hmm, you're right, that is used only for decoding. Since I've implemented MessagePack v5, which restricts UTF-8 for strings, the only way I personally used is to use unsafes.

Like this: https://github.com/3Hren/cocaine-http-proxy/blob/master/src/route/app.rs#L305

**Comment by 3Hren** [comment]
Well, it seems that no one hurts if we implement `Serialize` for `Raw` the same way using different constructor functions explicitly (like `from_string` and `from_bytes` or using `From` trait), and with a common `new` that checks UTF-8 validity itself.
