### ISSUE TITLE
unpack msgpack map type

### ISSUE THREAD

**Issue by HeathKang** [3Hren/msgpack-rust#166]
Hi，I want to know how to unpack msgpack map type by RMP. Because I can't find a ```read_map``` function in RMP decode document. I am a new in rust and use lua msgpack pack a table type in redis, and I want read redis data and unpack lua table msgpack type by rust.
Thanks a lot!

**Comment by 3Hren** [comment]
Unpack into what?
The lowest level function for this is [`read_map_len`](https://docs.rs/rmp/0.8.7/rmp/decode/fn.read_map_len.html), but I don't think this is what you're looking for.

So check [this](https://github.com/3Hren/msgpack-rust/blob/master/rmp-serde/tests/decode.rs#L281).

**Comment by HeathKang** [comment]
Thanks for all, I have used 
```
use rmpv::Value as Value_rmp;
use rmpv::decode;

let val: Value_rmp = decode::read_value(&mut &data[..]).unwrap();
```
to decode, and  it works now
