### ISSUE TITLE
Relax assertion on negative extension types

### ISSUE THREAD

**Issue by dani-garcia** [3Hren/msgpack-rust#174]
I'm using the `rmpv` crate to serialize some data to MessagePack, some of this data contains dates, so the data needs to be serialized as a Timestamp extension type, with type `-1`. See spec here: https://github.com/msgpack/msgpack/blob/master/spec.md#timestamp-extension-type.

When trying to serialize that data (using `write_value(&mut buf, &Value::Ext(-1, <data_here>)`) the `rmp` crate panics at the following line:
https://github.com/3Hren/msgpack-rust/blob/e96d118/rmp/src/encode/mod.rs#L260

At the moment I'm using a local copy of the crate with that assertion removed, but it would be helpful if that assertion could be relaxed to at least allow the type `-1`.

**Comment by 3Hren** [comment]
Oh, it was added https://github.com/msgpack/msgpack/pull/209 almost a year ago. Okay, I agree that now we can remove this assertion.
