### ISSUE TITLE
Implement serde's `is_human_readable` to return `false`

### ISSUE THREAD

**Issue by aszkid** [3Hren/msgpack-rust#176]
Currently, the Serializer and Deserializer pairs in `rmp-serde` do not implement [`is_human_readable`](https://docs.serde.rs/serde/trait.Serializer.html#method.is_human_readable). As a consequence of this, types that support a more compact representation serialize and deserialize inefficiently: for example, IPv4 addresses should take something like 4 bytes, but currently use an annoying 17 bytes, as they serialize as regular strings (my qualm stems from serializing [`IpNet`](https://docs.rs/ipnet/2.0.0/ipnet/#serde-support) structs).

Has this issue been discussed before? While I do think this is a reasonable request to make, it is nevertheless a breaking change (mentioned on the serde docs—previously serialized types that support a compact representation will fail at deserialization).

I am currently using a [forked repo](https://github.com/aszkid/msgpack-rust/tree/rmps-human_readable) implementing this change; merging would be extremely easy from a technical point of view (an effective 2 lines of code addded), but there is a discussion to be had.

**Comment by daboross** [comment]
I'm in full support of this.

If msgpack-rust is against making breaking changes like this, maybe it could be done as an added option, like `StructMapSerializer`?

**Comment by joshtriplett** [comment]
https://github.com/3Hren/msgpack-rust/pull/257 (together with the serde fix in https://github.com/serde-rs/serde/pull/1888 ) should fix this.
