### ISSUE TITLE
Implement `serde::Serializer` and `serde::Deserializer` for `rmpv::Value`, TAKE 2

### ISSUE THREAD

**Issue by izolyomi** [3Hren/msgpack-rust#188]
I've recently found this lib that seems pretty usable in general. However, being used to `serde_json`, I was looking for serializing `Value` with rmp-serde right away. First I thought it was not implemented at all (see reasons below), but finding closed issue #101 it probably was, but got broken since. Why I think it doesn't work?

I'm trying to implement two-step request processing by first extracting a request envelope and dispatching the payload to the appropriate request processor. I need `rmpv::Value` for this because the dispatcher cannot expect any strongly typed messages in advance. The relevant parts of source code are the following:

```
use serde_derive::{Deserialize, Serialize};

#[derive(Clone, Debug, Deserialize, Serialize)]
pub(crate) struct Request
{
    target: String,
    payload: rmpv::Value,
}
```

This immediately triggers the following error message:

```
error[E0277]: the trait bound `rmpv::Value: messages::_IMPL_SERIALIZE_FOR_Request::_serde::Deserialize<'_>` is not satisfied
  --> src/messages.rs:16:5
   |
16 |     payload: rmpv::Value,
   |     ^^^^^^^ the trait `messages::_IMPL_SERIALIZE_FOR_Request::_serde::Deserialize<'_>` is not implemented for `rmpv::Value`
   |
   = note: required by `messages::_IMPL_SERIALIZE_FOR_Request::_serde::de::SeqAccess::next_element`
```
Note that without the `rmpv::Value`, the rest of the code compiles like charm. Do you have any suggestion what I did wrong or how I could work around the possibly broken implementation?

**Comment by 3Hren** [comment]
Did you set `with-serde` feature?

**Comment by izolyomi** [comment]
No, I didn't even know it exists, there was zero documentation on it, thanks for pointing it out.

As I just manually read the `Cargo.toml` of the `rmpv` crate, understood the feature and enabled it, it compiles now as expected, so I can confirm it's definitely not broken.

It'd be nice to see it documented somewhere, I'd never expect that I have to enable a "hidden" feature on a crate to achieve intuitive behavior.

**Comment by fwcd** [comment]
Agreed, I have pretty much exactly the same use case as

> I'm trying to implement two-step request processing by first extracting a request envelope and dispatching the payload to the appropriate request processor.

and it was non-obvious from the documentation that I needed the `with-serde` feature and that the undocumented (?) function [`rmpv::ext::from_value`](https://github.com/3Hren/msgpack-rust/blob/69f90c636705966d8b6855dae6f7cc49afe273ba/rmpv/src/ext/de.rs#L16) was the one I was looking for.

Great library though!

**Comment by tqwewe** [comment]
Sadly this doesn't show up in the docs since when docs.rs builds, it doesn't have with-serde enabled. Would be awesome to have this in the docs, I also missed this.
