### ISSUE TITLE
rmp-serde version 0.14

### ISSUE THREAD

**Issue by elichai** [3Hren/msgpack-rust#189]
Hey,
I see that you bumped the version of `rmp-serde` a year ago, and on crates.io it's still `0.13.x`.
Why is that? Did you just forget to publish or is there something wrong with 0.14?

Thanks,
Elichai.

**Comment by elichai** [comment]
@3Hren ping

**Comment by kornelski** [comment]
@3Hren ping again. If you're too busy to make releases, please add others to the project. I could help.

**Comment by kornelski** [comment]
@3Hren ping again. If you're too busy to make releases, please add others to the project. I could help.

**Comment by 3Hren** [comment]
You're sadly right, no time for this project ATM :(
I have plans for developing, including `no_std` support and further serde improvements, but currently not now.

So I've added @kornelski and @daboross as contributors here and @kornelski on crates.io.
