### ISSUE TITLE
Integration with serde

### ISSUE THREAD

**Issue by 3Hren** [3Hren/msgpack-rust#19]
From https://github.com/serde-rs/serde/issues/96.

I see it as an optional feature instead of `rustc_serialize` (or maybe leave both of them?).

- [x] Investigate how to cook serde (compile some examples, see how json serialization/deserialization is done etc.)
- [x] Implement a decoder.
- [x] Implement an encoder.

**Comment by dswd** [comment]
Without knowing that you are working on it too, I started my own approach (https://github.com/dswd/serde-msgpack).
It is not finished yet but you can use parts of it if you like.

**Comment by 3Hren** [comment]
Awesome!

Right now I'm working on zero-copy value encoder/decoder. After it is done I had a plan to move forward with this issue, but if you have already done with it you can create a PR (if you want).

I cannot borrow, because you hasn't marked the license type.

**Comment by dswd** [comment]
I planned to make it LGPL first but as I took the marker code from you I think it is only fair to license it as MIT too.
