### ISSUE TITLE
Failure to transcode with serde_transcode

### ISSUE THREAD

**Issue by photex** [3Hren/msgpack-rust#197]
Howdy!

I'm using serde_transcode to go from msgpack -> json without a problem. Sadly, once I needed to go the other direction I'm unable to.

```
let msg = r#"{
    "channel": "/kmsg/test",
    "message": [0, "Hello"]
}"#;

// assert that the test json string can be parsed and decoded.
let res = serde_json::from_str::<serde_json::Value>(msg);
assert!(res.is_ok());

let mut deserializer = serde_json::Deserializer::from_str(msg);
let mut bytes = Vec::new();
let mut serializer = rmps::Serializer::new(&mut bytes);

let res = transcode(&mut deserializer, &mut serializer);
dbg!(&res);
assert!(res.is_ok()); // <--- test fails on this assert
assert!(!bytes.is_empty());
```

The error I'm getting is `attempt to serialize struct, sequence or map with unknown length`, with the line an column listed of the first member of the object.

**Comment by 3Hren** [comment]
I'm a bit unaware of how serde-transcode works. Seems like it tries to serialize array with `None` length provided, which is not supported by msgpack.

**Comment by 3Hren** [comment]
Seems serde-transcode works the streaming way, so when the json deserializer hits the array it cannot determine its `size_hint()` without reading the entire array. Unfortunately, that means that json->msgpack transcoding cannot be utilized. 

Only fully deserialize and then serialize.
