### ISSUE TITLE
rmp-serde::Error's Display implementation excludes error information 

### ISSUE THREAD

**Issue by daboross** [3Hren/msgpack-rust#198]
Right now, if you try to display (print using `to_string()` or `{}` formatting) any decoding or encoding error produced by `rmp-serde`, you get the following string:

```
error while decoding value
```

For example, consider this program:

```
fn main() {
    let _x: u32 = match rmp_serde::from_slice(&[]) {
        Ok(v) => v,
        Err(e) => panic!("error occurred: {}", e),
    };
}
```

This produces the following message:

```
thread 'main' panicked at 'error occurred: error while decoding value', src/main.rs:4:19
```

It tells us there's an error, but not much else.

---

The issue, I believe, is caused by these lines:

https://github.com/3Hren/msgpack-rust/blob/88c46511cc9bb9cabce8b53d46a0062b7b88a9a0/rmp-serde/src/decode.rs#L70-L74

Particularly, `description` here is limited to returning a static string, and thus contains no context nor information on what the error is actually about.

The `Debug` implementation is still useful in that it gives information on what error happened. But most programs expect `Display` to give at least as much information as `Debug` gives about errors, and `Debug` only outputs type names, no descriptions of what's happened.

Ideally, the `Display` implementation would provide an informative message, giving at least some indication of what went wrong during the encoding or decoding process. If a change to this is welcome, I can submit a PR - just wanted to file an issue first to identify the problem.

**Comment by 3Hren** [comment]
Yes, the `Display` implementation was written using old `Error` conventions. Since now much of the `Error` methods are deprecated it will be more convenient to rewrite the `Display` to provide additional information.

>If a change to this is welcome, I can submit a PR - just wanted to file an issue first to identify the problem.
It would be great!

**Comment by daboross** [comment]
> Yes, the `Display` implementation was written using old `Error` conventions. Since now much of the `Error` methods are deprecated it will be more convenient to rewrite the `Display` to provide additional information.

Ah, makes sense!

I've submitted #199 for adding more detail to the `Display` impls.
