### ISSUE TITLE
Structs in lists ignore ext handler settings

### ISSUE THREAD

**Issue by daboross** [3Hren/msgpack-rust#205]
When using `with_struct_map`, I generally expected structs being encoded as maps to be applied recursively, to all structs serialized. This is sometimes the case, but if any structs are nested within options or arrays, then the behavior is no longer applied. Structures within arrays or options are serialized as arrays.

For instance, this version of the `round_struct_as_map` test fails:

```rust
#[test]
fn round_struct_as_vec_map() {
    use rmps::decode::from_slice;
    use rmps::to_vec_named;

    #[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
    struct Dog1 {
        name: String,
        age: u16,
    }
    #[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
    struct Dog2 {
        age: u16,
        name: String,
    }

    let dog1 = Dog1 {
        name: "Frankie".into(),
        age: 42,
    };

    let data = vec![dog1];

    let serialized: Vec<u8> = to_vec_named(&data).unwrap();
    let deserialized: Vec<Dog2> = from_slice(&serialized).unwrap();

    let dog2 = &deserialized[0];

    assert_eq!(dog2.name, "Frankie");
    assert_eq!(dog2.age, 42);
}
```

With the error message: `Syntax("invalid type: string \"Frankie\", expected u16")`.

**Comment by 3Hren** [comment]
Well, the way how it currently works is wrong. Probably constructing `Compound` value with `self` helps. I'll try to take a look at this the next weekend.

**Comment by daboross** [comment]
@3Hren

I hope I'm not imposing too much, but is it alright if I take a crack at this?

I have an idea for how we might solve this, and remove some of the boilerplate of ext encoders at the same time. What if instead of having configuration options wrap the entire `Serializer`, we have them wrap a small core "config" structure instead?

The default configuration structure would just implement default options, and `StructTupleConfig` and `StructMapConfig` would wrap another configuration, changing only the relevant options. It would be just like the current `ext` encoders, but only having to change a few methods like `write_struct_len` and `write_struct_field` rather than the whole `serde::Serializer` API.
