### ISSUE TITLE
Deserialization issue across 0.13 and 0.14

### ISSUE THREAD

**Issue by stusmall** [3Hren/msgpack-rust#219]
We recently upgraded one of our services to rmp-serde 0.14.  As we started testing we saw that services still using 0.13 would fail to de-serialize the messages produced by the upgraded instance.  I tested the same release and only reverted back to 0.13 and it worked just fine so I'm fairly confident that the regression was introduced by the new release.  

Unfortunately it's a fairly large, complex and closed source code base.  I'm going to try and reduce down to a repro case to one that I can share.  If it helps the error message I am getting back is "TypeMismatch(FixMap(1))" but I doubt that is much use without more context.

**Comment by kornelski** [comment]
There were bug fixes around handling of enums in `Option`. If it's caused by this change, then I'm afraid it'd be difficult to make it backwards-bug-compatible.
