### ISSUE TITLE
TryFrom<Value> for T

### ISSUE THREAD

**Issue by KillTheMule** [3Hren/msgpack-rust#227]
While working on https://github.com/KillTheMule/nvim-rs, I felt the need for good error reporting, which includes failed conversions from `Value` to an expected type. On selected occasions, I used

```Rust
  let arr = match read_value(reader)? {
    Value::Array(v) => v,
    val => Err(NotAnArray(val))?,
  };
```

for it. But this seems very much like a job for `TryFrom<Value> for Vec<Value>`. There could of course be several other variants as well.

Would such a PR be of interest?

**Comment by kornelski** [comment]
Yeah, that sounds sensible.
