### ISSUE TITLE
Possible typo in rmp-serde config.rs?

### ISSUE THREAD

**Issue by vext01** [3Hren/msgpack-rust#239]
https://github.com/3Hren/msgpack-rust/blob/3f25c4d26434f3e4fccc25dfcea38a72ecba812b/rmp-serde/src/config.rs#L50-L55

> This is the most compat representation.

I'm left wondering if `compat` is a typo of `compact`, or it is a shortening of `compatible`.

Thanks

**Comment by kornelski** [comment]
Yeah, I think it was meant to be compact
