### ISSUE TITLE
Encoding/decoding of 0i32 fails

### ISSUE THREAD

**Issue by mbudde** [3Hren/msgpack-rust#24]
```rust
extern crate rmp as msgpack;
extern crate rustc_serialize;

use rustc_serialize::{Encodable, Decodable};
use msgpack::{Encoder, Decoder};

fn main() {
    let val = 0i32;
    let mut buf = Vec::new();
    val.encode(&mut Encoder::new(&mut buf)).unwrap();
    let mut decoder = Decoder::new(&buf[..]);
    let res: i32 = Decodable::decode(&mut decoder).unwrap();
    assert_eq!(val, res);
}
```
fails with
```
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: TypeMismatch(PositiveFixnum(0))', /home/rustbuild/src/rust-buildbot/slave/stable-dist-rustc-linux/build/src/libcore/result.rs:729
```
Change `val` to any non-zero value and the program runs without errors. Tested on both version 0.4 and 0.5.

**Comment by mbudde** [comment]
Seems like the problem is caused by two things: 1) `write_sint` encodes 0 as `NegativeFixnum(0u8)` which gets written as `0x0` by `write_fixval`, and 2) that `read_i{8,16,32,64}_loosely` doesn't handle the `PositiveFixnum` case.

Is there a reason `write_sint` does not encode 0 ≤ val ≤ 127 as `PositiveFixnum(val as u8)`?

**Comment by 3Hren** [comment]
Thanks, I'll take a look today.

**Comment by 3Hren** [comment]
The documentation for `write_sint` says that the function **always** uses signed integer representation even if the value can be more efficiently represented using unsigned integer encoding.

For `0` value it should use a 2-byte sequence. It's a bug.

However I suppose the `Encoder` must use the most effective representation.

**Comment by 3Hren** [comment]
Sorry for a long response, please check the PR it should fix your issue.

**Comment by mbudde** [comment]
Great :+1: PR does indeed seem to fix the issue.
