### ISSUE TITLE
from_read_ref taking 20 seconds for 180mb

### ISSUE THREAD

**Issue by jacktuck** [3Hren/msgpack-rust#243]
I'm new to rust & msgpack so thought i'd see if this is expected performance and if there's any significantly faster ways to use this crate. I have a file (it happens to be geolocation data from a maxmind csv database). It's approximately 180mb. I need to be able to deserialise the data as quick as possible and much quicker than a second if possible.

This is roughly what i'm doing, i've stripped all the extraneous stuff.
```
#[derive(Debug, PartialEq, Deserialize, Serialize)]
struct Record {
    network: String,
    geoname_id: String,
    registered_country_geoname_id: String,
    represented_country_geoname_id: String,
    is_anonymous_proxy: String,
    is_satellite_provider: String,
    postal_code: String,
    latitude: String,
    longitude: String,
    accuracy_radius: String
}

fn main() -> std::io::Result<()> {
    let f = File::open("src/ips.csv")?; // maxmind geolite ipv4 database ~180mb
    let mut r = csv::Reader::from_reader(BufReader::new(f));
    
    let mut records = Vec::new();
    for result in r.deserialize() {
        let record: Record = result?;
        records.push(record);
    }
    
    let buf = rmp_serde::to_vec(&records).unwrap();
  
    let now = Instant::now();
    let values: Vec<Record> = rmp_serde::from_read_ref(&buf).unwrap();
    println!("time {}", now.elapsed().as_secs());

    Ok(())
}
```

I also dumped `buf` into a file to interrogate it. It's ~180mb. Which i thought would be smaller with message pack?

**Comment by kornelski** [comment]
CSV is close to optimal format for string columns — it only needs one byte as a separator, and it's hard to beat that.

Perhaps you could see some size savings if you used numeric types and booleans instead of `String`. These strings need individual heap allocations, so they will be relatively slow.

**Comment by jacktuck** [comment]
@kornelski That makes sense. Following that suggestion gets down to about 140mb and 10 seconds to deserialize, which is better but still not where i need it to be.

**Comment by KillTheMule** [comment]
I'll just ask the famous basic question of anything performance related in rust: Did you run in release mode?

**Comment by jacktuck** [comment]
@jacktuck it's a good question. After changing some fields from string to int/bool and using release flag it's down to 2 seconds.

**Comment by kornelski** [comment]
If you want really small file, you could try using [bincode](https://lib.rs/crates/bincode) and [snappy](https://lib.rs/crates/snap).

**Comment by jacktuck** [comment]
Thanks! I think msgpack is the wrong solution for me for sure. Currently looking at capnproto or flatbuffers. Will close this though since it seems like the slowness was my end.
