### ISSUE TITLE
nested options break

### ISSUE THREAD

**Issue by thedavidmeister** [3Hren/msgpack-rust#245]
`Some(Some(...))` round trips to an error

```
thread 'tests::round_trip' panicked at 'called `Result::unwrap()` on an `Err` value: FromBytes("wrong msgpack marker FixPos(1)")', src/libcore/result.rs:1187:5
stack backtrace:
```

**Comment by kornelski** [comment]
Yup, it's broken :(

**Comment by kornelski** [comment]
It seems that msgpack has a hardcoded shortcut for handling `null`, and that approach is not compatible with nested options.

Can someone have a look how serde-json solves it and apply a similar solution?
