### ISSUE TITLE
Question about zero-copy decoding

### ISSUE THREAD

**Issue by akiradeveloper** [3Hren/msgpack-rust#258]
In README, you claim this feature 

> Zero-copy value decoding

but I don't have any idea how this is implemented and on what condition it happens.

Consider we have a message type

```rust
struct Message {
  #[serde(with = "serde_bytes")]
  x: Vec<u8>
}
```

and serialize it. My understanding is it is encoded as Binary format in the byte sequence which is even efficient than Array of u8.

However, this struct is **owned**. Owned means every resource of the struct is independent from the original buffer to decode. Thus, this struct doesn't support zero-copy decoding even if it uses serde-bytes.

How do I define the struct to benefit from zero-copy decoding?

**Comment by kornelski** [comment]
I'm not sure, since I haven't used zero-copy decoding myself. Have you tried using `&[u8]` instead?

**Comment by akiradeveloper** [comment]
Not yet but I will try.

I see. @3Hren initially wrote the code and README and the project was handed over to you.

**Comment by sergeyzenchenko** [comment]
@akiradeveloper you should use &[u8] and &str instead of Vec and String to archive zero-copy decoding. But keep in mind that you original byte array should live long enough.

**Comment by sergeyzenchenko** [comment]
Also you need to provide lifetime for this struct. Here is example from our code base
```rust
#[derive(Debug, Serialize, Deserialize, Clone, Eq, PartialEq)]
pub struct EventsBatchRef<'a> {
    pub start_seq_id: u32,
    pub end_seq_id: u32,
    pub compression_type: u8,
    pub real_size: u32,
    pub payload: &'a [u8],
}
```

**Comment by akiradeveloper** [comment]
@sergeyzenchenko Yes, thanks for the information. I've already done this here https://github.com/akiradeveloper/lol/blob/v0.5.2/lol-core/src/lib.rs#L99

```rust
enum CommandB<'a> {
    Noop,
    Snapshot {
        membership: HashSet<Id>,
    },
    ClusterConfiguration {
        membership: HashSet<Id>,
    },
    Req {
        core: bool,
        #[serde(with = "serde_bytes")]
        message: &'a [u8]
    }
}
```

I should've closed this issue.
