### ISSUE TITLE
Is msgpack self-describing?

### ISSUE THREAD

**Issue by vedantroy** [3Hren/msgpack-rust#273]
Hi,

Thanks for making this. From the msgpack website, it looks like msgpack is self-describing: https://msgpack.org/index.html.

Does this mean, a this crate will be able to, for example, deserialize msgpack data that is created by Swift? And can this crate serialize data to msgpack that can be then read by Swift?

I'm asking b/c I read through the encode/decode code in the rmp-serde crate, and it seemed like stuff was serialized/deserialized without field names.

**Comment by daboross** [comment]
It is indeed self-describing.

The default mode for this crate, however, is to use integer indices instead of field names. To use field names instead, you need to use the `to_vec_named` method or https://docs.rs/rmp-serde/0.15.4/rmp_serde/config/struct.StructMapConfig.html

**Comment by vedantroy** [comment]
Thanks, this makes sense.
