### ISSUE TITLE
Serialize enums without associated data as strings?

### ISSUE THREAD

**Issue by vedantroy** [3Hren/msgpack-rust#275]
Can there be an option to serialize enums without any associated data as strings?

**Comment by Cightline** [comment]
I too would like enums as strings.

**Comment by avkonst** [comment]
I think it is quite important feature to keep msgpack serializer in alignment with json serailizer. Currently the workaround is to implement Serialize manually for enums, which is not ideal....

**Comment by vedantroy** [comment]
This is now implemented in https://github.com/3Hren/msgpack-rust/pull/286
