### ISSUE TITLE
Error "invalid type: byte array, expected a sequence" when it works with serde_json

### ISSUE THREAD

**Issue by mimoo** [3Hren/msgpack-rust#291]
I'm getting the following error on something that should work (and works with serde_json).

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax("invalid type: byte array, expected a sequence")

I posted a minimal repro here: https://github.com/jonasbb/serde_with/issues/372#issuecomment-932804303

**Comment by mimoo** [comment]
it works with bincode also:

```
    // bincode
    let encoded: Vec<u8> = bincode::serialize(&a).unwrap();
    println!("bincode encoded: {:?}", encoded);
    let decoded: A = bincode::deserialize(&encoded[..]).unwrap();
    println!("bincode decoded: {:?}", decoded);
    println!();
```

**Comment by kornelski** [comment]
Given [this comment](https://github.com/jonasbb/serde_with/issues/372#issuecomment-93281141) I'm not sure if there's anything this crate needs to change?

**Comment by mimoo** [comment]
Looks like it! Sorry about that ^^
