### ISSUE TITLE
Implement PartialEq for rmp_serde errors

### ISSUE THREAD

**Issue by makaleks** [3Hren/msgpack-rust#293]
I use custom error using enums and store rmp_serde::encode::Error and rmp_serde::decode::Error inside one of its variants. To use assert_eq! in tests I need to implement PartialEq for this types myself. These errors may worth adding #[derive(PartialEq)], may not they?

**Comment by kornelski** [comment]
These enums may contain `io::Error` which isn't comparable. You can implement `PartialEq` manually yourself, or use `matches!` instead of `==`.

**Comment by makaleks** [comment]
@kornelski , thank you, that was surprising for me. Was not familiar with `matches!`
