### ISSUE TITLE
Make ReadRefReader.buf public

### ISSUE THREAD

**Issue by wbenny** [3Hren/msgpack-rust#300]
Hi,
I want to deserialize stream of MessagePack structures with zero-copy.

But when I create ReadRefReader with:

```rust
    let contents = std::fs::read(&path).unwrap();
    let mut deserializer = Deserializer::from_read_ref(&contents);
```

... and then deserialize a first struct:

```rust
    let msg = Message::deserialize(&mut deserializer)?;
```

I have no way of knowing where did the deserializer end.

However, if I would add this into the `impl<'de, R> Deserializer<ReadRefReader<'de, R>>`:
```rust
    pub fn get_buf(&self) -> &'de [u8] {
        self.rd.buf
    }
```

... and used it like this:

```rust
    let mut buf = &contents[..];

    let mut result = Vec::new();

    loop {
        let mut deserializer = Deserializer::from_read_ref(&buf[..]);

        if let Ok(event) = Message::deserialize(&mut deserializer) {
            result.push(event);
        }
        else {
            break;
        }

        buf = deserializer.get_buf();
    }

```

It would work.

So the question is - am I missing something? Is there a way how to deserialize streaming MessagePack structs from buffer reference? If not - would it be possible to add the `get_buf()` method? And if not... could you think of a better way how to implement this?

**Comment by kornelski** [comment]
I haven't tried parsing concatenated messages like this, so I'm not sure if the reader is reading only as little as necessary, but if it is, then you should be able to use `Cursor` to reuse the reader across multiple calls, or even `&mut &[u8]` IIRC, since it also implements `Read` and remembers position read.

**Comment by wbenny** [comment]
Thanks for the prompt response!

Cursor, unfortunatelly, does not have AsRef trait, therefore, it cannot be wrapped into ReadRefReader. As for the `&mut &[u8]`.. I don't think I understand it.

**Comment by wbenny** [comment]
I think I got it (or did I?), but... it produces an error.

```rust
pub fn parse<'a>(contents: &'a [u8]) -> Vec<Message<'a>> {
    let mut result = Vec::new();

    let mut deserializer = Deserializer::from_read_ref(&mut contents.as_ref());

    loop {
        if let Ok(message) = Message::deserialize(&mut deserializer) {
            result.push(message);
        }
        else {
            break;
        }
    }

    result
// ^^^^^^ returns a value referencing data owned by the current function
}
```

**Comment by wbenny** [comment]
So, this is working - in a sense that the `result` is properly filled:

```rust
pub fn parse(contents: &[u8]) -> Vec<Message> {
    let mut result = Vec::new();

    let cursor = &mut contents.as_ref(); // or &mut &contents
    let mut deserializer = Deserializer::from_read_ref(cursor);

    loop {
        let r = Message::deserialize(&mut deserializer);
        if let Ok(message) = r {
            result.push(message);
        }
        else {
            break;
        }
    }

    // result
    Vec::new()
}
```

However, I still can't return the result from the function. I think I understand the reason, but I don't know how to work around it. Except for maybe rewriting the method as `fn parse(contents: &mut &[u8])`.

**Comment by kornelski** [comment]
You should be able to make your function take `&'a impl Read`.

Don't call `.as_ref()` on regular references. It's a necessary evil for `Option` or generic `AsRef`, but otherwise it causes nothing but trouble.

**Comment by wbenny** [comment]
But there isn't `Deserialize::from_slice` method. Only `rmp_serde::from_slice` that returns `T`. Also, for some reason I feel more and more lost with each of your new comment :) I still have no idea how to properly resolve this issue.

**Comment by kornelski** [comment]
I mean this:

```rust
#[derive(serde::Serialize, serde::Deserialize)]
struct Test {
    msg: String,
}

fn main() {
    let mut ser = Vec::new();

    ser.append(&mut rmp_serde::to_vec(&Test {msg: "Hello".into()}).unwrap());
    ser.append(&mut rmp_serde::to_vec(&Test {msg: "World".into()}).unwrap());

    /////////////////////

    let mut reader = ser.as_slice();

    let one: Test = rmp_serde::from_read(&mut reader).unwrap();
    let two: Test = rmp_serde::from_read(&mut reader).unwrap();

    println!("{} {}", one.msg, two.msg);
}

```

You don't need direct use of deserializer or any special buffer manipulation, because `Read` already works with slices.

**Comment by wbenny** [comment]
Thanks, I really appreciate you answering, however, I stressed multiple times that I'm specifically interested in zero-copy deserialization, and this example, unfortunatelly, doesn't work:

```rust
#[derive(serde::Serialize, serde::Deserialize)]
struct Test<'a> {
    msg: &'a str,
}

fn main() {
    let mut ser = Vec::new();

    rmp_serde::encode::write(&mut ser, &Test {msg: "Hello"}).unwrap();
    rmp_serde::encode::write(&mut ser, &Test {msg: "World"}).unwrap();

    /////////////////////

    let mut reader = ser.as_slice();

    let one: Test = rmp_serde::from_read_ref(&mut reader).unwrap();
    let two: Test = rmp_serde::from_read_ref(&mut reader).unwrap();

    println!("{} {}", one.msg, two.msg);
}
```

**Comment by kornelski** [comment]
Ah, yes. I forgot about this complication.

**Comment by wbenny** [comment]
Thanks @kornelski !
