### ISSUE TITLE
rmp_serde fails to fill buffer from file when decoding

### ISSUE THREAD

**Issue by gluax** [3Hren/msgpack-rust#315]
```rust
let mut msgpack = std::fs::OpenOptions::new()
        .read(true)
        .write(true)
        .create(true)
        .open("foo.msgpack")
        .expect("f");

    rmp_serde::encode::write(&mut msgpack, &132).expect("write");
    let num: i32 = rmp_serde::decode::from_read(&mut msgpack).expect("read");
    dbg!(num);
```

Results in `read: InvalidMarkerRead(Error { kind: UnexpectedEof, message: "failed to fill whole buffer" })`.

Happens with structs as well, but just wanted to simplify the issue.

**Comment by kornelski** [comment]
It means it expected there to be more data. It may happen if msgpack file was created with a different version or has a structure that doesn't map to the type you're deserializing.

**Comment by gluax** [comment]
I'm using the same version in the above example, and the types are explicit. So I don't understand what could be going wrong. If I'm doing something wrong, please point it out because I certainly don't see why the above code would be invalid :c.

**Comment by kornelski** [comment]
Oh, I see. You're trying to read past the end of the file. Reading doesn't rewind. It continues *after* position of last write, where there is nothing.

**Comment by gluax** [comment]
That was silly of me! Thanks for that!
