### ISSUE TITLE
Variant encoding/decoding policy.

### ISSUE THREAD

**Issue by 3Hren** [3Hren/msgpack-rust#32]
MessagePack has no specification about how to encode variant types. Thus we are free to do whatever we want.

Every Rust variant value can be represented as a tuple of index and a value, and we encode/decode them this way by default, but the given chose may be not ideal for you.

The first solution I've imaging is to introduce enum policies as a template parameter attached to `Encoder` and `Decoder` with default value of course.

**Comment by seppo0010** [comment]
The problem also rises in json. Following rustc-serialize json implementation might be a good option.

**Comment by 3Hren** [comment]
Partially solved for encoding structs, for enums the strategy will be the same.

**Comment by 3Hren** [comment]
Closed with #44.
