### ISSUE TITLE
Raw Binary support

### ISSUE THREAD

**Issue by seppo0010** [3Hren/msgpack-rust#37]
Is Raw Binary supported at the moment? I believe `Vec<u8>` is serialized as an array of numbers instead of a Raw String. Is there a wrapper that can be used?

**Comment by 3Hren** [comment]
Hi!

Please take a look here: https://github.com/3Hren/msgpack-rust/blob/master/rmp-serde/tests/serializer.rs#L339. This is only currently supported with Serde serializer.

**Comment by seppo0010** [comment]
Cool, thanks!
