### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by 3Hren** [3Hren/msgpack-rust#45]
- [x] Make table with badges for each subcrate.
- [x] Documentation with examples for `rmp`.
- [x] Documentation with examples for `rmp-serialize`
- [x] Documentation with examples for `rmp-serde`.
- [x] Documentation links to sub crates.

**Comment by mikedilger** [comment]
+1
I'd especially like to see examples with rmp-serde

**Comment by 3Hren** [comment]
Updated.
