### ISSUE TITLE
Streaming interface?

### ISSUE THREAD

**Issue by dpc** [3Hren/msgpack-rust#51]
Hi,

I'm trying to figure out if and how to feed deserializer chunks of data (eg. from a socket). In other serde-based libraries (eg. bincode) I can find a Reader and Writer support: http://tyoverby.com/bincode/bincode/rustc_serialize/struct.DecoderReader.html

How to do that with msgpack-rust?

**Comment by 3Hren** [comment]
Currently all readers are stateless.

You can feed chunks of data to `BufReader` over `TcpStream` and try to decode it each time using `read_value_ref`.

```rust
let mut rd = BufReader::with_capacity(4096, stream);
loop {
    let nread = match rd.fill_buf() {
        Ok([]) => {} // EOF
        Ok(buf) => {
            let mut cur = Cursor::new(buf);
            let val = match rmp::decode::read_value_ref(&mut cur) {
                Ok(val) => val,
                Err(err) => break,                        
            };
            cur.position() as usize
        }
        Err(err) => break,
    }
    rd.consume(nread);
}
```

I can implement stateful `Deserializer` support, but it takes time.

**Comment by dpc** [comment]
Thanks for the answer!

**Comment by 3Hren** [comment]
I think it can be closed for now.
