### ISSUE TITLE
How to read i32, if I don't know whether it is signed?

### ISSUE THREAD

**Issue by alexkamp** [3Hren/msgpack-rust#54]
hey, 

Some language interfaces for msgpack decide dynamically whether they use signed or unsigned integers. Specifically, I am working with java. Java does not have unsigned types, so if I pack an int (32 bits) the msgpack Java implementation chooses the best possible coding. If the value is small enough and positive, this may as well be FixPos, U8 or U16. 

read_i32_loosely handles FixNeg, I8, I16 and I32, but no unsigned types. read_u32_loosely handles all unsigned types, but not the signed types. So if I know that the next value in a buffer fits into an i32, but it may be decoded as U16 (or FixPos), how do I read it?

**Comment by 3Hren** [comment]
Hi!

There are (undocumented yet) family of functions `read_i64_fit` (`i32`, `u16` etc.) which does exactly what you want.

**Comment by alexkamp** [comment]
Ah, okay. Thanks.
