### ISSUE TITLE
Compilation error: no method 'join' for Vec

### ISSUE THREAD

**Issue by Ilphrin** [3Hren/msgpack-rust#55]
Hi,

I tried using your package through [vim-markdown-composer](https://github.com/euclio/vim-markdown-composer), and when compiling all the rust's packages, rmp fail and give me this message:
```
rmp-0.7.3/src/value.rs:58:22: 58:32 error: no method named 'join' found for type 'collections::vec::Vec<collections::string::String>' in the current scope
```

**Comment by 3Hren** [comment]
This is strange, because there are tests that checks that behavior.

Need more information: toolchain, platform, OS.

**Comment by Ilphrin** [comment]
I'm using:
- Lubuntu 64 Bits
- Rust 1.2.0
- Cargo 0.4.0-nightly

I don't see any 'join' function in [Rust doc for Vec](https://doc.rust-lang.org/collections/vec/struct.Vec.html)

**Comment by 3Hren** [comment]
There are concat extensions: https://doc.rust-lang.org/nightly/std/slice/trait.SliceConcatExt.html#tymethod.join

**Comment by Ilphrin** [comment]
Well, I'm not much used to Rust programming, but if it exists does that mean I need an earlier version of Rust?

**Comment by 3Hren** [comment]
Seems like it was added in 1.3

**Comment by Ilphrin** [comment]
I've updated to Rust 1.5 and now everything seems to be working. Sorry for the misunderstanding, I'll contact the developper of the vim plugin to add a note about the minimum version of Rust needed. Thanks for your help 3Hren!

**Comment by 3Hren** [comment]
You're welcome!
