### ISSUE TITLE
Decoding arbitrary messages conveniently

### ISSUE THREAD

**Issue by squareduck** [3Hren/msgpack-rust#59]
Hi, I'm struggling with decoding arbitrary messages with msgpack-rust.
In examples in this repo it's know ahead of time what "type" decoded message will have, but what if messages can vary in structure?

Here's an example scenario.

A server needs to send several events to the client:
```
// Using pseudocode here
{ name: "event1", a: 12, b: ["text", "some more"] }
{ name: "event2" c: { d: "yet again" } }
```
These two events have different "types" and can't be decoded into same struct.

How do I decode a group of different messages properly?

**Comment by 3Hren** [comment]
Hi!

You can work with generic `Value` directly without prior deserializing into structs like [here](https://github.com/3Hren/msgpack-rust/blob/master/rmp/tests/func/decode/value.rs#L91). I'd recommend you to follow this way.

Alternatively if your variant types are finite number, i.e. can be represented as ADT, you can derive custom deserializer as [here](https://github.com/3Hren/msgpack-rust/blob/master/rmp-serde/tests/de_macro.rs#L218) for example, but this is more tricky.

**Comment by squareduck** [comment]
3Hren, thanks for quick reply.
Exactly what I needed. There's going to be finite number of message types, so custom deserializer seems tempting. I'll explore both options.

Thanks for awesome library!
