### ISSUE TITLE
Encode fields using their names as keys

### ISSUE THREAD

**Issue by SuperFluffy** [3Hren/msgpack-rust#62]
I wanted to use `msgpack-rust` as a drop-in replacement for `serde-json`. As it turns out, `rmp-serde` is ignoring field names in structs when serializing the data, which is very unfortunate. I produce a lot of data from numerical simulations and analyze them in Python, which is why I would like to be able to deserialize the `msgpack`ed data using proper keys (without the need to write a custom deserialization strategy and keep it updated with changes to my `rust` structs). Is there a way to have `rmp` serialize struct fields using their names, i.e. much more akin to what `serde-json` does? For example, the code sample at the bottom of this post is deserialized as:

```
{'field_2': [1, [[[1.0, 1.0], [3.0, 3.0]]]],
 'field_1': [0, [[[2, 2], [4, 4]]]],
 'field_3': [2, [[[0, [[[2, 2], [4, 4]]]], [1, [[[1.0, 1.0], [3.0, 3.0]]]]]]]}
```

where I was expecting something closer to (i.e. not necessarily taking into account the name of the top-level struct):

```
{'field_2': [('cs',[1.0, 1.0]), ('ds',[3.0, 3.0])],
 'field_1': [('xs',[2, 2]), ('ys',[4, 4])],
 'field_3': [('foo', [('xs',[2, 2]), ('ys',[4, 4])]), ('bar', [('cs',[1.0, 1.0]), ('ds',[3.0, 3.0])])]}
```

Notice too, that the `serde(rename="name")` is being ignored.

``` rust
use std::io::BufWriter;
use msgpack::Serializer;

#[derive(Serialize)]
enum Custom {
    Foo(Foo),
    Bar(Bar),
    FooBar(Vec<Custom>),
}

#[derive(Serialize)]
struct Foo {
    #[serde(rename="a")]
    xs: Vec<u64>,
    #[serde(rename="b")]
    ys: Vec<u64>,
}

#[derive(Serialize)]
struct Bar {
    cs: Vec<f64>,
    ds: Vec<f64>,
}

fn main() {
    let foo = Foo { xs: vec![2;2], ys: vec![4;2] };
    let bar = Bar { cs: vec![1.0;2], ds: vec![3.0;2] };
    let foobar = vec![Custom::Foo(foo), Custom::Bar(bar), ];

    let mut map = BTreeMap::new();

    let foo = Foo { xs: vec![2;2], ys: vec![4;2] };
    let bar = Bar { cs: vec![1.0;2], ds: vec![3.0;2] };
    map.insert("field_1".to_owned(), Custom::Foo(foo));
    map.insert("field_2".to_owned(), Custom::Bar(bar));
    map.insert("field_3".to_owned(), Custom::FooBar(foobar));

    let f = File::create("test.txt").unwrap();
    let mut writer = BufWriter::new(f);

    map.serialize(&mut Serializer::new(&mut writer)).unwrap()
}
```

**Comment by 3Hren** [comment]
It's possible using custom writers. Check [this](https://github.com/3Hren/msgpack-rust/blob/master/rmp-serde/tests/se_macro.rs#L42).

**Comment by Enet4** [comment]
How should we do this in the latest version? The link above was not a permalink, and the tests are no longer in the same place. Honestly, I believe that an easier way to override this optimization should be considered, if it doesn't exist yet.

**Comment by 3Hren** [comment]
Well, I have accidentally broken this issue, sorry. Will fix in the next patch release.

**Comment by 3Hren** [comment]
Here: https://github.com/3Hren/msgpack-rust/blob/master/rmp-serde-tests/tests/encode.rs#L136

**Comment by Enet4** [comment]
That link got outdated again. Fortunately I managed to find the equivalent test in the master's HEAD. [This link](https://github.com/3Hren/msgpack-rust/blob/432f3ef27db8726b24bc31bf3173d6d27d6ca9a7/rmp-serde/tests/encode_derive.rs#L136) is fixed to the commit, so hopefully it won't invalidate so quickly.

```rust
    struct StructMapWriter;

    impl VariantWriter for StructMapWriter {
        fn write_struct_len<W: Write>(&self, wr: &mut W, len: u32) ->
            Result<Marker, ValueWriteError>
        {
            write_map_len(wr, len)
        }

        fn write_field_name<W: Write>(&self, wr: &mut W, key: &str) ->
            Result<(), ValueWriteError>
        {
            write_str(wr, key)
        }
    }
```
