### ISSUE TITLE
encode vec<u8> as messagepack bin-family in rustc

### ISSUE THREAD

**Issue by eqv** [3Hren/msgpack-rust#63]
Using rustc, is there a way to encode vec<u8> as bin data object instead of array of ints? The later takes up nearly twice as much space. I cannot just wrap Vec<u8> and Implement Encodable for that struct manually since the Encoder doesn't allow for calls to write_bin or to access to the underlying writer.
Is there a way to achieve the same with serde?

**Comment by 3Hren** [comment]
Hi,

As far as I remember there is no way to achieve this functionality with RustcSerialize. However, Serde provides a special helper `Bytes` wrapper.
See [this](https://github.com/3Hren/msgpack-rust/blob/master/rmp-serde/tests/se.rs#L293) test.

**Comment by eqv** [comment]
Thanks for the fast reply. In that case i will have to use Bytes in all structs instead of Vec<u8> but they should have the same interface, or I have to implement Serializable on all structs including Vec<u8> by hand to use Serializer.serialize_bytes right?

**Comment by 3Hren** [comment]
I'd recommend you to create non-owning unsized helper mirror struct with `Bytes` wrapper instead of `Vec` each time you want to serialize and implement `std::borrow::Borrow` trait for it.

```rust
struct Foo {
    buf: Vec<i32>,
    val: i32,
}

#[derive(Serialize)]
struct FooView<'a> {
    buf: Bytes<'a>,
    val: i32
}

impl<'a> ::std::borrow::Borrow<FooView<a'>> for Foo {
...
}
```

This will be lightweight operation. Then, you can serialize it directly:

```rust
let foo = Foo::new();

foo.borrow().serialize(&mut Serializer::new(&mut buf)).ok().unwrap();
```

**Comment by eqv** [comment]
Thank you very much, I think this issue can be closed.
