### ISSUE TITLE
read_str_ref is useless?

### ISSUE THREAD

**Issue by cmbrandenburg** [3Hren/msgpack-rust#69]
Maybe I misunderstand the purpose of `read_str_ref`, but the function seems to have two problems:
1. It returns `&[u8]` on success, not `&str`.
2. It doesn't give any indication on success how many bytes it read from the input buffer. How does the caller know how to extract the next message-packed field in the input buffer following the string it just read?

The second problem is what makes `read_str_ref` useless (as I understand it). Suppose the following snippet:

``` rust
let r: &[u8]  = { /* generate input here */ };

// Read a string from the input.
let x = rmp::decode::read_str_ref(r).unwrap();
println!("{:?}", x);

// How to read next field? The `r` slice still points to the extracted string,
// not the next field in the input
```

Here's the current signature for `read_str_ref`.

`fn read_str_ref(rd: &[u8]) -> Result<&[u8], DecodeStringError>`

How about something like this instead?

`fn read_str_ref(rd: &mut &[u8]) -> Result<(&str, &[u8]), DecodeStringError>`

On success, the tuple `(&str, &[u8])` pairs the string just read along with a slice to the beginning of the input immediately following the string. This would allow the caller to continue reading from the buffer.

``` rust
let r: &[u8]  = { /* generate input here */ };

// Read a string from the input.
let (x, mut r) = rmp::decode::read_str_ref(r).unwrap();
println!("{:?}", x);

// Read next field from the input.
let x = rmp::decode::read_u32_loosely(&mut r).unwrap();
println!("{:?}", x);
```

**Comment by 3Hren** [comment]
You're right, `read_str_ref` is a rudiment.

I thought about to accept `ReadBuf`, which encapsulates `[u8]`, `Cursor<[u8]>` etc. and to return number of bytes (not chars!) read to be able to consume after read.

Your suggestion is good too. I'll think about it today.

**Comment by 3Hren** [comment]
Please check this commit: https://github.com/3Hren/msgpack-rust/commit/cf8537a6496f8d66d3b2b8378f29560f3da7788c
