### ISSUE TITLE
Support new serde map/seq serialization API

### ISSUE THREAD

**Issue by knsd** [3Hren/msgpack-rust#74]
Release 0.8.0 contains significant breaking changes, see [release notes](https://github.com/serde-rs/serde/releases/tag/v0.8.0) for details.

**Comment by 3Hren** [comment]
Yeah, I've already seen that release notes, looks good. After upgrade we should also bump our version up to v0.10, because rmp-serde exports serde as a public dependency.

But for v0.10 there should be also other reason, new feature for example.

**Comment by 3Hren** [comment]
Will be in #80.
