### ISSUE TITLE
Consider merging rmp, rmp-serde, and rmp-serialize using cargo features.

### ISSUE THREAD

**Issue by euclio** [3Hren/msgpack-rust#79]
Having to wrap `Value` in `rmp_serde::Value` to get `Serialize` adds complexity to the implementation and puts additional weight on the user.

It might be best to use exclusive `cargo` features to pick which serialization implementation you want to use.

**Comment by 3Hren** [comment]
Hmm, I can split `rmp` crate into `rmp` and `rmp-value` with optional serialize/deserialize support for the latter (using cargo features, yeah).

Will do this week.

**Comment by euclio** [comment]
Hey @3Hren, are you still planning to tackle this?

**Comment by 3Hren** [comment]
Yep, currently I'm in the middle of large refactoring, that includes byteorder version bump. This issue is the next.

**Comment by euclio** [comment]
Great. I'm in the process of implementing a Serializer for Value, so I'll wait to make a PR til the refactor is complete.

**Comment by 3Hren** [comment]
Done: there are `rmp` and `rmpv` (with Value) crates now.
