### ISSUE TITLE
Using the msgpack bin format family?

### ISSUE THREAD

**Issue by jimfulton** [3Hren/msgpack-rust#82]
Is it possible to use the bin format family for encoding and decoding? When I try to encode [u8], I get arrays of ints and when I try to decode binary data I get errors. I see bin support in the rmp sources.

**Comment by 3Hren** [comment]
Shortly: it is.

To be able to answer your question correctly I need more information. Do you use serde for encoding/decodyng `[u8]` or do it directly using rmp?

**Comment by jimfulton** [comment]
Excellent, thanks for the speedy reply. I'm willing to use whatever works. :)

I just stumbled across a test in rmp_serde, pass_bin8_into_bytebuf, that answers half of my question. I assume there's another test that answers the other half.  So maybe I'm good.

Is there a way to use rmp without serde or rustc-serialize?  If so, a pointer would be interesting.

**Comment by 3Hren** [comment]
Of course. There are primitive functions like [this](https://github.com/3Hren/msgpack-rust/blob/master/rmp/src/encode.rs#L666) and [this](https://github.com/3Hren/msgpack-rust/blob/master/rmp/src/encode.rs#L688). I'm not using them widely, so feel free to suggest better interface if you like to.

**Comment by jimfulton** [comment]
Cool. Thanks.
