### ISSUE TITLE
read_i/uXX_loosely should be looser :)

### ISSUE THREAD

**Issue by jimfulton** [3Hren/msgpack-rust#85]
They should accept any integer input that matches the target type.

For example read_i64_loosely, should accept [1].  It should even accept an unsigned 64-bit integer as long as the value is in the range of 64-bit signed integers.

msgpack is sometimes used with dynamic languages, that will often use whatever encoding is most efficient without regard to an unknown target type in a statically-typed language.

(In my case, messages are being generated by Python.)

**Comment by 3Hren** [comment]
I'm currently working exactly on that issue :)

**Comment by jimfulton** [comment]
Excellent.

**Comment by 3Hren** [comment]
With RMP >=0.8 there are now writing functions that use the most compact representation and reading functions that automatically cast numeric types.
All dependent crates should use these features including serde serializing/deserializing.
