### ISSUE TITLE
Serialization without newlines?

### ISSUE THREAD

**Issue by SuperFluffy** [3Hren/msgpack-rust#91]
**EDIT:** I realize now that this question might not actually make a lot of sense. I am going to try and serialize these structs one after the other and see if I can get msgpack to deserialize them.

**SOLUTION:** Using a `std::io::Cursor` around a `Vec<u8>` for serializing into and deserializing from, msgpack is quite capable of doing what I want, I think:

```rust
    let foo = Foo { xs: vec![1.423; 4], ys: vec![5; 3] };
    let bar = Bar { x: 1.423, y: 5 };

    let mut bufcursor = Cursor::new(Vec::new());

    foo.serialize(&mut Serializer::new(&mut bufcursor)).ok().unwrap();
    bar.serialize(&mut Serializer::new(&mut bufcursor)).ok().unwrap();

    bufcursor.seek(SeekFrom::Start(0));
    let mut deserializer = rmp_serde::Deserializer::new(bufcursor);

    let foo_de: Foo = Deserialize::deserialize(&mut deserializer).unwrap();
    let bar_de: Bar = Deserialize::deserialize(&mut deserializer).unwrap();
```

---

I want my program to  serialize a struct, write it to a file, followed by a `\n`. For example, I expected to have some configuration struct on the first line, and 10 lines with some runtime statistics, each taken some time apart. If this was json, it would maybe look like this: `{"config": ...}\n{"state": ..., "statistics": ...}\n{"state": ..., "statistics": ...}\n...`.

Now, instead of 11 lines, I ended up with 47, and I am not really sure why. Is that a feature of the msgpack? Is there a way to fix this or, when deserializing, distinguish between blocks of structs?

**Comment by 3Hren** [comment]
I'm not sure I understand what is this issue about. :( Can you explain more verbosely?

**Comment by SuperFluffy** [comment]
I have a simulation. After some time has passed, I want to write out the simulation's state as well as it's statistics, so that I could a) plot data, but also b) restart it at a specific point.

So far, I was serializing this (state,statistics) pair (in form of a struct) with `serde_json`, with one json-string per line. When restarting, I would just find the line I needed, read it from the file, and deserialize it.

But my problem is that I lose accuracy in my `f64`: the binary representation after serialization+deserialization is not the original one. But in my systems I need to have exactly the same numbers before and after.

That's the reason why I was looking into some way of doing binary serialization and stumbled over `msgpack`. My problem was however: how do I tell `rmp_serde` where one (state,statistics) pair starts and where it ends? Using `\n' didn't make any sense anymore, as that's a text, not a binary concept.

**Comment by 3Hren** [comment]
Without iteratively deserializing the whole buffer it's not possible in the common case, because of various binary representation for integers (it can have 1,2,3,5 and 9 bytes per integer depending on size).

**Comment by 3Hren** [comment]
However you can just iteratively deserialize structs over your dataset buffer wrapped with cursor, pointing you on how many bytes were consumed. Then you can pause and resume your iterations.

**Comment by SuperFluffy** [comment]
Yeah, the latter was what I was now thinking of. It's not the most elegant method (as it requires essentially constructing the same kind of thing over and over), but since I am doing that very very rarely it's not so bad. :-)

**Comment by SuperFluffy** [comment]
Maybe having some kind of helper method like this `.bytes_read` in `bincode` would be useful? Have a look at the first example on this page (pointed out to me by @dtolnay).

http://tyoverby.com/bincode/bincode/serde/struct.Deserializer.html
