### ISSUE TITLE
Provide a method on deserializers that returns the number of bytes read from the underlying reader

### ISSUE THREAD

**Issue by euclio** [3Hren/msgpack-rust#95]

**Comment by 3Hren** [comment]
Wrap reader with `Cursor`.

**Comment by euclio** [comment]
That works, but it ends up being a fair amount of ceremony for extracting a value that the deserializer could already save internally.

**Comment by 3Hren** [comment]
But otherwise you will pay for what you don't need in case you don't need bytes counting. I can do impl<R> for Cursor<R> where R: Read with `position()` method exposed. Does it simplify your case?

**Comment by euclio** [comment]
Gotcha. Yeah, that would be a nice impl to have!

**Comment by 3Hren** [comment]
Done in https://github.com/3Hren/msgpack-rust/commit/2e5f0f1252d7537ba94e082d064f0b6b9b0b97b2 and published in 0.12.1.
Please check it out.
