### ISSUE TITLE
Can't deserialize tuple struct

### ISSUE THREAD

**Issue by kyrias** [3Hren/msgpack-rust#96]
I'm trying to serialize and deserialize an `secretbox::Key` which is a tuple struct from the sodiumoxide crate, but when trying to deserialize it with `rmp_serde` I just get ```error while decoding value```.  I'm not sure if this is a bug in msgpack-rust, or if sodiumoxide is breaking it however.

**Comment by 3Hren** [comment]
Can I have an example?

**Comment by kyrias** [comment]
```
extern crate sodiumoxide;
extern crate serde;
extern crate rmp;
extern crate rmp_serde;

use serde::{Serialize, Deserialize};
use sodiumoxide::crypto::secretbox;

fn main() {
    let key: secretbox::Key = secretbox::gen_key();

    let mut buf = Vec::new();
    key.serialize(&mut rmp_serde::Serializer::new(&mut buf)).unwrap();

    let mut de = rmp_serde::Deserializer::new(&buf[..]);
    let res: secretbox::Key = Deserialize::deserialize(&mut de).unwrap();
}
```

panicks with

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TypeMismatch(Array32)', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:870
```

**Comment by 3Hren** [comment]
Seems like it's a bug in `sodiumoxide`. Here it serializes keys using bytes: https://github.com/dnaq/sodiumoxide/blob/master/src/newtype_macros.rs#L46, but tries to deserialize using `seq`: https://github.com/dnaq/sodiumoxide/blob/master/src/newtype_macros.rs#L58.

We expect symmetric behaviour (i.e to deserialize using `visit_bytes` method).

**Comment by kyrias** [comment]
Ah.  Is this something serde expects as well, or is it something msgpack-rust expects? hmm

**Comment by 3Hren** [comment]
I think only `Serializer`/`Deserializer` implementers, that see difference between sequence and bytes expect so. For example we pack bytes as binary https://github.com/3Hren/msgpack-rust/blob/master/rmp-serde/src/encode.rs#L383 and unpack binary using bytes https://github.com/3Hren/msgpack-rust/blob/master/rmp-serde/src/decode.rs#L358, because MessagePack is a self-describable format.

Anyway symmetry for serializing and deserializing should never harm.

**Comment by 3Hren** [comment]
However you can implement `serde::Deserializer` trait by wrapping `rmp_serde::Deserializer` with `forward_to_deserialize!` all except `bytes`. But I think it's quite a hack.

**Comment by kyrias** [comment]
Fixed in sodiumoxide
