### ISSUE TITLE
Serde 0.9

### ISSUE THREAD

**Issue by 3Hren** [3Hren/msgpack-rust#97]
Serde 0.9 is out and we're need to support it in order to be at the bleeding edge.

**Comment by dtolnay** [comment]
Please publish a release with this.

**Comment by 3Hren** [comment]
Done.

**Comment by euclio** [comment]
Is Serde 0.9 support coming for rmpv?

**Comment by 3Hren** [comment]
Sure. May be tomorrow.

**Comment by 3Hren** [comment]
Done.
