### ISSUE TITLE
Example in docs does not compile

### ISSUE THREAD

**Issue by cjcole** [3Hren/msgpack-rust#99]
The "struct Human" example here:

https://docs.rs/rmp-serde/0.11.0/rmp_serde/

does not compile.

After adding a missing "extern crate serde;" I get this:

rmp_serde_test$ cargo run
   Compiling rmp_serde_test v0.1.0 (file:///.../rmp_serde_test)
error[E0277]: the trait bound `&mut rmp_serde::Serializer<'_, rmp_serde::encode::StructArrayWriter>: serde::Serializer` is not satisfied
  --> src/main.rs:22:9
   |
22 |     val.serialize(&mut Serializer::new(&mut buf)).unwrap();
   |         ^^^^^^^^^ the trait `serde::Serializer` is not implemented for `&mut rmp_serde::Serializer<'_, rmp_serde::encode::StructArrayWriter>`

error: aborting due to previous error

error: Could not compile `rmp_serde_test`.

rmp_serde_test$ cat Cargo.toml
[package]
name = "rmp_serde_test"
version = "0.1.0"
authors = [...]

[dependencies]
serde = "0.9.6"
serde_derive = "0.9.6"
rmp = "0.8.2"
rmp-serde = "0.11.0"

rmp_serde_test$ rustup show
Default host: x86_64-apple-darwin

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-x86_64-apple-darwin

active toolchain
----------------

nightly-x86_64-apple-darwin (directory override for '/.../rmp_serde_test')
rustc 1.17.0-nightly (c49d10207 2017-02-07)

(same result with stable versus nightly)

**Comment by dtolnay** [comment]
The rmp-serde crate has not been updated to serde 0.9 yet. For now you will need to use serde 0.8 until a new release is published - #97.

**Comment by dtolnay** [comment]
Try it with the new rmp-serde 0.12.0 and serde 0.9.

**Comment by cjcole** [comment]
> Try it with the new rmp-serde 0.12.0 and serde 0.9.

rmp-serde 0.12.0 works well, thanks.
